package cz.janakdom.backend.service;

import cz.janakdom.backend.model.AffectedEntityEntity;
import cz.janakdom.backend.model.RailroadEntity;
import cz.janakdom.backend.model.TypeOfInterventionEntity;
import org.springframework.stereotype.Service;

import java.util.*;

@Service(value = "deviceService")
public class SerieService {

    public List<RailroadEntity> getSerieRailRoads() {
        List<RailroadEntity> data = new ArrayList<RailroadEntity>();
        int i = 0;
        data.add(new RailroadEntity("010", "(Praha -) Kolín - Česká Třebová"));
        data.add(new RailroadEntity("011", "Souhrnná doprava Praha - Kolín"));
        data.add(new RailroadEntity("012", "Pečky - Kouřim"));
        data.add(new RailroadEntity("013", "Bošice - Bečváry"));
        data.add(new RailroadEntity("014", "Kolín - Ledečko"));
        data.add(new RailroadEntity("015", "Přelouč - Prachovice"));
        data.add(new RailroadEntity("016", "Borohrádek - Holice - Moravany - Chrudim - Heřmanův Městec"));
        data.add(new RailroadEntity("017", "Česká Třebová - Moravská Třebová - Chornice"));
        data.add(new RailroadEntity("018", "Choceň - Litomyšl"));
        data.add(new RailroadEntity("019", "Česká Třebová - Lanškroun"));
        data.add(new RailroadEntity("020", "(Praha -) Velký Osek - Hradec Králové - Choceň"));
        data.add(new RailroadEntity("021", "Týniště nad Orlicí - Letohrad"));
        data.add(new RailroadEntity("022", "Častolovice - Solnice"));
        data.add(new RailroadEntity("023", "Doudleby nad Orlicí - Rokytnice v Orlických horách"));
        data.add(new RailroadEntity("024", "Ústí nad Orlicí - Štíty"));
        data.add(new RailroadEntity("025", "Dolní Lipka - Hanušovice"));
        data.add(new RailroadEntity("026", "Týniště nad Orlicí - Otovice zastávka"));
        data.add(new RailroadEntity("028", "Opočno pod Orlickými horami - Dobruška"));
        data.add(new RailroadEntity("030", "(Pardubice -) Jaroměř - Liberec"));
        data.add(new RailroadEntity("031", "Souhrnná doprava Pardubice - Hradec Králové - Jaroměř"));
        data.add(new RailroadEntity("032", "Jaroměř - Trutnov"));
        data.add(new RailroadEntity("034", "Smržovka - Josefův Důl"));
        data.add(new RailroadEntity("035", "Tanvald - Železný Brod"));
        data.add(new RailroadEntity("036", "Liberec - Tanvald - Harrachov"));
        data.add(new RailroadEntity("037", "Liberec - Černousy"));
        data.add(new RailroadEntity("038", "Raspenava - Bílý Potok pod Smrkem"));
        data.add(new RailroadEntity("039", "Frýdlant v Čechách - Jindřichovice pod Smrkem"));
        data.add(new RailroadEntity("040", "Chlumec nad Cidlinou - Trutnov"));
        data.add(new RailroadEntity("041", "Hradec Králové - Jičín - Turnov, Hněvčeves - Smiřice"));
        data.add(new RailroadEntity("042", "Martinice v Krkonoších - Rokytnice nad Jizerou"));
        data.add(new RailroadEntity("043", "Trutnov - Žacléř"));
        data.add(new RailroadEntity("044", "Kunčice nad Labem - Vrchlabí"));
        data.add(new RailroadEntity("045", "Trutnov - Svoboda nad Úpou"));
        /*data.add(new RailroadEntity("046", "Lomnice nad Popelkou - Stará Paka"));
        data.add(new RailroadEntity("047", "Trutnov - Teplice nad Metují"));
        data.add(new RailroadEntity("060", "Poříčany - Nymburk"));
        data.add(new RailroadEntity("061", "Nymburk - Jičín"));
        data.add(new RailroadEntity("062", "Chlumec nad Cidlinou - Křinec"));
        data.add(new RailroadEntity("063", "Bakov nad Jizerou - Kopidlno"));
        data.add(new RailroadEntity("064", "Mšeno - Mladá Boleslav - Lomnice nad Popelkou"));
        data.add(new RailroadEntity("070", "Praha - Turnov"));
        data.add(new RailroadEntity("071", "Nymburk - Mladá Boleslav"));
        data.add(new RailroadEntity("072", "Lysá nad Labem - Ústí nad Labem západ"));
        data.add(new RailroadEntity("073", "Ústí nad Labem-Střekov - Děčín"));
        data.add(new RailroadEntity("074", "Čelákovice - Neratovice"));
        data.add(new RailroadEntity("076", "Mělník - Mšeno"));
        data.add(new RailroadEntity("080", "Bakov nad Jizerou - Jedlová"));
        data.add(new RailroadEntity("081", "Děčín - Rumburk"));
        data.add(new RailroadEntity("083", "Rumburk - Dolní Poustevna"));
        data.add(new RailroadEntity("084", "Rumburk - Panský - Mikulášovice"));
        data.add(new RailroadEntity("085", "Krásná Lípa - Panský"));
        data.add(new RailroadEntity("086", "Liberec - Česká Lípa"));
        data.add(new RailroadEntity("087", "Lovosice - Česká Lípa"));
        data.add(new RailroadEntity("088", "Rumburk - Ebersbach (Sachs)"));
        data.add(new RailroadEntity("089", "Liberec - Rybniště"));
        data.add(new RailroadEntity("090", "(Praha -) Kralupy nad Vltavou - Ústí nad Labem - Děčín"));
        data.add(new RailroadEntity("091", "Souhrnná doprava Praha - Kralupy nad Vltavou"));
        data.add(new RailroadEntity("092", "Neratovice - Kralupy nad Vltavou"));
        data.add(new RailroadEntity("093", "Kralupy nad Vltavou - Kladno"));
        data.add(new RailroadEntity("094", "Vraňany - Lužec nad Vltavou"));
        data.add(new RailroadEntity("095", "Vraňany - Straškov - Zlonice"));
        data.add(new RailroadEntity("096", "Roudnice nad Labem - Straškov - Libochovice"));
        data.add(new RailroadEntity("097", "Lovosice - Teplice v Čechách"));
        data.add(new RailroadEntity("098", "Děčín - Bad Schandau"));
        data.add(new RailroadEntity("110", "Kralupy nad Vltavou - Louny"));
        data.add(new RailroadEntity("111", "Kralupy nad Vltavou - Velvary"));
        data.add(new RailroadEntity("113", "Lovosice - Most"));
        data.add(new RailroadEntity("114", "Lovosice - Louny - Postoloprty"));
        data.add(new RailroadEntity("120", "Praha - Kladno - Lužná u Rakovníka - Rakovník"));
        data.add(new RailroadEntity("121", "Hostivice - Podlešín"));
        data.add(new RailroadEntity("122", "Praha - Hostivice - Rudná u Prahy"));
        data.add(new RailroadEntity("123", "Most - Žatec západ"));
        data.add(new RailroadEntity("124", "Lužná u Rakovníka - Žatec - Chomutov"));
        data.add(new RailroadEntity("125", "Krupá - Kolešovice"));
        data.add(new RailroadEntity("126", "Most - Louny - Rakovník"));
        data.add(new RailroadEntity("130", "Ústí nad Labem - Chomutov"));
        data.add(new RailroadEntity("131", "Ústí nad Labem - Úpořiny - Bílina"));
        data.add(new RailroadEntity("132", "Děčín - Oldřichov u Duchcova"));
        data.add(new RailroadEntity("133", "Chomutov - Jirkov"));
        data.add(new RailroadEntity("134", "Teplice v Čechách - Litvínov"));
        data.add(new RailroadEntity("135", "Most - Moldava v Krušných horách"));
        data.add(new RailroadEntity("137", "Chomutov - Vejprty"));
        data.add(new RailroadEntity("140", "Chomutov - Karlovy Vary - Cheb"));
        data.add(new RailroadEntity("141", "Karlovy Vary dolní nádraží - Merklín"));
        data.add(new RailroadEntity("142", "Karlovy Vary dolní nádraží - Johanngeorgenstadt"));
        data.add(new RailroadEntity("144", "Nová Role - Chodov - Loket - Krásný Jez"));
        data.add(new RailroadEntity("145", "Sokolov - Kraslice - Zwotental"));
        data.add(new RailroadEntity("146", "Cheb - Luby u Chebu"));
        data.add(new RailroadEntity("147", "Františkovy Lázně - Bad Brambach"));
        data.add(new RailroadEntity("148", "Cheb - Hranice v Čechách"));
        data.add(new RailroadEntity("149", "Karlovy Vary dolní nádraží - Mariánské Lázně"));
        data.add(new RailroadEntity("160", "Plzeň - Žatec"));
        data.add(new RailroadEntity("161", "Rakovník - Bečov nad Teplou"));
        data.add(new RailroadEntity("162", "Rakovník - Mladotice"));
        data.add(new RailroadEntity("163", "Protivec - Bochov"));
        data.add(new RailroadEntity("164", "Kadaň-Prunéřov - Kadaň - Vilémov u Kadaně - Kaštice / Kadaňský Rohozec"));
        data.add(new RailroadEntity("170", "(Praha -) Beroun - Plzeň - Cheb"));
        data.add(new RailroadEntity("171", "Souhrnná doprava Praha - Beroun"));
        data.add(new RailroadEntity("172", "Zadní Třebaň - Lochovice"));
        data.add(new RailroadEntity("173", "Praha-Smíchov - Beroun"));
        data.add(new RailroadEntity("174", "Beroun - Rakovník"));
        data.add(new RailroadEntity("175", "Rokycany - Nezvěstice"));
        data.add(new RailroadEntity("176", "Chrást u Plzně - Radnice"));
        data.add(new RailroadEntity("177", "Pňovany - Bezdružice"));
        data.add(new RailroadEntity("178", "Svojšín - Bor"));
        data.add(new RailroadEntity("179", "Cheb - Marktredwitz"));
        data.add(new RailroadEntity("180", "Plzeň - Domažlice - Furth im Wald"));
        data.add(new RailroadEntity("181", "Nýřany - Heřmanova Huť"));
        data.add(new RailroadEntity("182", "Staňkov - Poběžovice"));
        data.add(new RailroadEntity("183", "Plzeň - Klatovy - Železná Ruda-Alžbětín"));
        data.add(new RailroadEntity("184", "Domažlice - Planá u Mariánských Lázní"));
        data.add(new RailroadEntity("185", "Horažďovice předměstí - Domažlice"));
        data.add(new RailroadEntity("190", "Plzeň - České Budějovice, Písek město - Protivín"));
        data.add(new RailroadEntity("191", "Nepomuk - Blatná"));
        data.add(new RailroadEntity("192", "Číčenice - Týn nad Vltavou"));
        data.add(new RailroadEntity("193", "Dívčice - Netolice"));
        data.add(new RailroadEntity("194", "České Budějovice - Černý Kříž"));
        data.add(new RailroadEntity("195", "Rybník - Lipno nad Vltavou"));
        data.add(new RailroadEntity("196", "České Budějovice - Summerau"));
        data.add(new RailroadEntity("197", "Číčenice - Volary - Nové Údolí"));
        data.add(new RailroadEntity("198", "Strakonice - Volary"));
        data.add(new RailroadEntity("199", "České Budějovice - Gmünd NÖ"));
        data.add(new RailroadEntity("200", "Zdice - Písek"));
        data.add(new RailroadEntity("201", "Tábor - Ražice"));
        data.add(new RailroadEntity("202", "Tábor - Bechyně"));
        data.add(new RailroadEntity("203", "Březnice - Strakonice"));
        data.add(new RailroadEntity("204", "Březnice - Rožmitál pod Třemšínem"));
        data.add(new RailroadEntity("210", "Praha - Vrané nad Vltavou - Čerčany"));
        data.add(new RailroadEntity("212", "Čerčany - Světlá nad Sázavou"));
        data.add(new RailroadEntity("220", "(Praha -) Benešov u Prahy - České Budějovice"));
        data.add(new RailroadEntity("221", "Souhrnná doprava Praha - Benešov u Prahy"));
        data.add(new RailroadEntity("222", "Benešov u Prahy - Trhový Štěpánov"));
        data.add(new RailroadEntity("223", "Olbramovice - Sedlčany"));
        data.add(new RailroadEntity("224", "Tábor - Horní Cerekev"));
        data.add(new RailroadEntity("225", "Havlíčkův Brod - Jihlava - Veselí nad Lužnicí"));
        data.add(new RailroadEntity("226", "Veselí nad Lužnicí - Gmünd NÖ"));
        data.add(new RailroadEntity("227", "Kostelec u Jihlavy - Slavonice"));
        data.add(new RailroadEntity("228", "Jindřichův Hradec - Obrataň"));
        data.add(new RailroadEntity("229", "Jindřichův Hradec - Nová Bystřice"));
        data.add(new RailroadEntity("230", "(Praha -) Kolín - Havlíčkův Brod"));
        data.add(new RailroadEntity("231", "Praha - Lysá nad Labem - Kolín"));
        data.add(new RailroadEntity("232", "Lysá nad Labem - Milovice"));
        data.add(new RailroadEntity("233", "Čelákovice - Mochov"));
        data.add(new RailroadEntity("235", "Kutná Hora - Zruč nad Sázavou"));
        data.add(new RailroadEntity("236", "Čáslav - Třemošnice"));
        data.add(new RailroadEntity("237", "Havlíčkův Brod - Humpolec"));
        data.add(new RailroadEntity("238", "Pardubice - Havlíčkův Brod"));
        data.add(new RailroadEntity("240", "Brno - Jihlava"));
        data.add(new RailroadEntity("241", "Znojmo - Okříšky"));
        data.add(new RailroadEntity("242", "Dobronín - Polná"));
        data.add(new RailroadEntity("243", "Moravské Budějovice - Jemnice"));
        data.add(new RailroadEntity("244", "Brno - Hrušovany nad Jevišovkou, Moravské Bránice - Oslavany"));
        data.add(new RailroadEntity("245", "Hrušovany nad Jevišovkou - Hevlín"));
        data.add(new RailroadEntity("246", "Břeclav - Znojmo"));
        data.add(new RailroadEntity("247", "Břeclav - Lednice"));
        data.add(new RailroadEntity("248", "Znojmo - Retz"));
        data.add(new RailroadEntity("250", "(Praha -) Havlíčkův Brod - Brno - Kúty"));
        data.add(new RailroadEntity("251", "Žďár nad Sázavou - Nové Město na Moravě - Tišnov"));
        data.add(new RailroadEntity("252", "Křižanov - Studenec"));
        data.add(new RailroadEntity("253", "Vranovice - Pohořelice"));
        data.add(new RailroadEntity("254", "Šakvice - Hustopeče u Brna"));
        data.add(new RailroadEntity("255", "Hodonín - Zaječí"));
        data.add(new RailroadEntity("256", "Čejč - Ždánice"));
        data.add(new RailroadEntity("257", "Kyjov - Mutěnice"));
        data.add(new RailroadEntity("260", "(Praha -) Česká Třebová - Brno"));
        data.add(new RailroadEntity("261", "Svitavy - Žďárec u Skutče"));
        data.add(new RailroadEntity("262", "Skalice nad Svitavou - Velké Opatovice - Chornice"));
        data.add(new RailroadEntity("270", "(Praha -) Česká Třebová - Přerov - Bohumín"));
        data.add(new RailroadEntity("271", "Prostějov - Konice - Dzbel - Chornice"));
        data.add(new RailroadEntity("273", "Červenka - Senice na Hané - Prostějov"));
        data.add(new RailroadEntity("274", "Litovel předměstí - Mladeč"));
        data.add(new RailroadEntity("275", "Olomouc - Drahanovice"));
        data.add(new RailroadEntity("276", "Suchdol nad Odrou - Budišov nad Budišovkou"));
        data.add(new RailroadEntity("277", "Suchdol nad Odrou - Fulnek"));
        data.add(new RailroadEntity("278", "Suchdol nad Odrou - Nový Jičín město"));
        data.add(new RailroadEntity("279", "Studénka - Bílovec"));
        data.add(new RailroadEntity("280", "Hranice na Moravě - Střelná"));
        data.add(new RailroadEntity("281", "Valašské Meziříčí - Rožnov pod Radhoštěm"));
        data.add(new RailroadEntity("282", "Vsetín - Velké Karlovice"));
        data.add(new RailroadEntity("283", "Horní Lideč - Bylnice"));
        data.add(new RailroadEntity("290", "Olomouc - Šumperk"));
        data.add(new RailroadEntity("291", "Zábřeh na Moravě - Šumperk"));
        data.add(new RailroadEntity("292", "Šumperk - Krnov"));
        data.add(new RailroadEntity("293", "Šumperk - Kouty nad Desnou/Sobotín"));
        data.add(new RailroadEntity("294", "Hanušovice - Staré Město pod Sněžníkem"));
        data.add(new RailroadEntity("295", "Lipová Lázně - Javorník ve Slezsku"));
        data.add(new RailroadEntity("296", "Velká Kraš - Vidnava"));
        data.add(new RailroadEntity("297", "Mikulovice - Zlaté Hory"));
        data.add(new RailroadEntity("298", "Třemešná ve Slezsku - Osoblaha"));
        data.add(new RailroadEntity("300", "Brno - Přerov (- Bohumín)"));
        data.add(new RailroadEntity("301", "Nezamyslice - Olomouc"));
        data.add(new RailroadEntity("302", "Nezamyslice - Morkovice"));
        data.add(new RailroadEntity("303", "Kojetín - Valašské Meziříčí"));
        data.add(new RailroadEntity("305", "Kroměříž - Zborovice"));
        data.add(new RailroadEntity("310", "Olomouc - Opava východ"));
        data.add(new RailroadEntity("311", "Valšov - Rýmařov"));
        data.add(new RailroadEntity("312", "Bruntál - Malá Morávka"));
        data.add(new RailroadEntity("313", "Milotice nad Opavou - Vrbno pod Pradědem"));
        data.add(new RailroadEntity("314", "Opava východ - Svobodné Heřmanice"));
        data.add(new RailroadEntity("315", "Opava východ - Hradec nad Moravicí"));
        data.add(new RailroadEntity("317", "Opava východ - Hlučín"));
        data.add(new RailroadEntity("318", "Kravaře ve Slezsku - Chuchelná"));
        data.add(new RailroadEntity("320", "Bohumín - Čadca"));
        data.add(new RailroadEntity("321", "Opava východ - Ostrava - Český Těšín"));
        data.add(new RailroadEntity("322", "Český Těšín - Frýdek Místek"));
        data.add(new RailroadEntity("323", "Ostrava - Valašské Meziříčí"));
        data.add(new RailroadEntity("324", "Frýdlant nad Ostravicí - Ostravice"));
        data.add(new RailroadEntity("325", "Studénka - Veřovice"));
        data.add(new RailroadEntity("326", "Dětmarovice - Petrovice u Karviné"));
        data.add(new RailroadEntity("330", "Přerov - Břeclav"));
        data.add(new RailroadEntity("331", "Otrokovice - Vizovice"));
        data.add(new RailroadEntity("332", "Hodonín - Holíč nad Moravou"));
        data.add(new RailroadEntity("334", "Kojetín - Tovačov"));
        data.add(new RailroadEntity("340", "Brno - Uherské Hradiště"));
        data.add(new RailroadEntity("341", "Staré Město u Uh.Hradiště - Vlárský průsmyk"));
        data.add(new RailroadEntity("342", "Bzenec - Moravský Písek"));
        data.add(new RailroadEntity("343", "Hodonín - Veselí nad Moravou - Vrbovce"));
        data.add(new RailroadEntity("346", "Újezdec u Luhačovic - Luhačovice"));
        data.add(new RailroadEntity("900", "Horní Hanychov - Ještěd"));
        data.add(new RailroadEntity("901", "Česká Kamenice - Kamenický Šenov (muzejní železnice)"));
        data.add(new RailroadEntity("904", "Mladějov na Moravě - Nová Ves u Kunčiny - Hřebeč doly (Mladějovská průmyslová dráha)"));
        data.add(new RailroadEntity("910", "Kolín-Sendražice - Býchory (Kolínská řepařská drážka)"));
        data.add(new RailroadEntity("911", "Zastávka u Brna MPŽ - Zbýšov-důl Jindřich (Muzeum průmyslových železnic)"));
        data.add(new RailroadEntity("912", "Velké Březno - Zubrnice - Verneřice/Úštěk (Zubrnická museální železnice)"));
        data.add(new RailroadEntity("913", "Zkušební okruh VUZ Velim"));
        data.add(new RailroadEntity("ML", "S41 Praha-Libeň - Roztoky u Prahy"));*/
        return data;
    }

    public List<TypeOfInterventionEntity> getSerieTypeOfIntervention() {
        List<TypeOfInterventionEntity> data = new ArrayList<TypeOfInterventionEntity>();
        int i = 0;
        data.add(new TypeOfInterventionEntity(++i, "Požár budov"));
        data.add(new TypeOfInterventionEntity(++i, "Požáry lokomotiv, vozů"));
        data.add(new TypeOfInterventionEntity(++i, "Požáry ostatní (vypalování kabelu apod.)"));
        data.add(new TypeOfInterventionEntity(++i, "Planý poplach"));
        data.add(new TypeOfInterventionEntity(++i, "Cvičení jednotek"));
        data.add(new TypeOfInterventionEntity(++i, "Likvidace nebezpečného hmyzu"));
        data.add(new TypeOfInterventionEntity(++i, "Únik (oleje z lokomotiv, apod.)"));
        data.add(new TypeOfInterventionEntity(++i, "Zimní opatení (sníh, ledové krápníky)"));
        return data;
    }

    public List<AffectedEntityEntity> getSerieAffectedEntity() {
        List<AffectedEntityEntity> data = new ArrayList<AffectedEntityEntity>();
        int i = 0;
        data.add(new AffectedEntityEntity(++i, "Arriva"));
        data.add(new AffectedEntityEntity(++i, "AWT"));
        data.add(new AffectedEntityEntity(++i, "ČD"));
        data.add(new AffectedEntityEntity(++i, "ČD Cargo"));
        data.add(new AffectedEntityEntity(++i, "LeoExpress"));
        data.add(new AffectedEntityEntity(++i, "RegioJet"));
        data.add(new AffectedEntityEntity(++i, "SŽ"));
        data.add(new AffectedEntityEntity(++i, "Jiný"));
        return data;
    }
}
